# Generated by Django 5.1.5 on 2025-02-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_students_course_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Course',
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(to='myapp.course'),
        ),
    ]
